class LogSession:
    """Class to hold logs generated during runtime
    """
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance.__normal_logs = ""
            cls._instance.__error_logs = ""
        return cls._instance

    def get_normal_logs(self) -> str:
        return self.__normal_logs

    def get_error_logs(self) -> str:
        return self.__error_logs

    def add_normal_log(self, log:str):
        """Adds a normal log and a newline character

        Args:
            log (str): log generated by the Logger
        """
        self.__normal_logs += log + "\n"

    def add_error_log(self, log:str):
        """Adds an error log and a newline character

        Args:
            log (str): log generated by the Logger
        """
        self.__error_logs += log + "\n"
